---
version: '3'
services:
  nginx:
    container_name: mt-nginx
    image: nginx:1.17
    volumes:
      - ./nginx-local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - iam_api
      - fulfillment_api
    ports:
      - "8080:80"
  db:
    container_name: mt-db
    image: postgres:12
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: d

  rabbitmq:
    container_name: mt-rabbitmq
    image: rabbitmq:3.8-management
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev

  redis:
    container_name: mt-redis
    image: redis:5

  iam_api:
    container_name: mt-iam
    image: gramedia/nusantara-iam-api
    environment:
      NUS_DEBUG: 'true'
      NUS_RABBITMQ_URL: amqp://dev:dev@rabbitmq:5672
      NUS_DB_PRIMARY: postgresql://dev:dev@db:5432/iam
      NUS_DB_REPLICA: postgresql://dev:dev@db:5432/iam
      NUS_REDIS_URL: redis://redis:6379/1

  fulfillment_api:
    container_name: mt-fulfillment
    image: gramedia/nusantara-fulfillment-api
    environment:
      NUS_DEBUG: 'true'
      NUS_RABBITMQ_URL: amqp://dev:dev@rabbitmq:5672
      NUS_DB_PRIMARY: postgresql://dev:dev@db:5432/fulfillment
      NUS_DB_REPLICA: postgresql://dev:dev@db:5432/fulfillment
      NUS_REDIS_URL: redis://redis:6379/2



