---
version: '3'
services:
  nginx:
    container_name: mt-nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx-local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - iam_api
      - fulfillment_api
      - cms_api
      - catalog_api
    ports:
      - "8080:80"
  db:
    container_name: mt-db
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  rabbitmq:
    container_name: mt-rabbitmq
    image: rabbitmq:3.8-management-alpine
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev

  redis:
    container_name: mt-redis
    image: redis:5-alpine
  admin:
    container_name: mt-admin
    image: gramedia/nusantara-admin:latest
    environment:
      NUS_DEBUG: 'true'
      NUS_RABBITMQ_URL: amqp://dev:dev@rabbitmq:5672
      NUS_DB_PRIMARY: postgresql://dev:dev@db:5432/iam
      NUS_DB_REPLICA: postgresql://dev:dev@db:5432/iam
      NUS_REDIS_URL: redis://redis:6379/1
  iam_api:
    container_name: mt-iam
    image: gramedia/nusantara-iam-api:latest
    environment:
      NUS_DEBUG: 'true'
      NUS_RABBITMQ_URL: amqp://dev:dev@rabbitmq:5672
      NUS_DB_PRIMARY: postgresql://dev:dev@db:5432/iam
      NUS_DB_REPLICA: postgresql://dev:dev@db:5432/iam
      NUS_REDIS_URL: redis://redis:6379/1

  fulfillment_api:
    container_name: mt-fulfillment
    image: gramedia/nusantara-fulfillment-api:feature_manage-warehouse
    environment:
      NUS_DEBUG: 'true'
      NUS_RABBITMQ_URL: amqp://dev:dev@rabbitmq:5672
      NUS_DB_PRIMARY: postgresql://dev:dev@db:5432/fulfillment
      NUS_DB_REPLICA: postgresql://dev:dev@db:5432/fulfillment
      NUS_REDIS_URL: redis://redis:6379/2

  cms_api:
    container_name: mt-cms
    image: gramedia/nusantara-cms-api:feature_cms
    environment:
      NUS_DEBUG: 'true'
      NUS_RABBITMQ_URL: amqp://dev:dev@rabbitmq:5672
      NUS_DB_PRIMARY: postgresql://dev:dev@db:5432/cms
      NUS_DB_REPLICA: postgresql://dev:dev@db:5432/cms
      NUS_REDIS_URL: redis://redis:6379/3
  catalog_api:
    container_name: mt-catalog
    image: gramedia/nusantara-catalog-api:feature_categories
    environment:
      NUS_DEBUG: 'true'
      NUS_RABBITMQ_URL: amqp://dev:dev@rabbitmq:5672
      NUS_DB_PRIMARY: postgresql://dev:dev@db:5432/cms
      NUS_DB_REPLICA: postgresql://dev:dev@db:5432/cms
      NUS_REDIS_URL: redis://redis:6379/3


