# This is an NGINX config file, intended for **local** development use
# only, within the docker-compose.yml file in this repo.
#
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, HEAD, PUT, PATCH, DELETE';
    add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,DNT,User-Agent,X-User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
    add_header 'Access-Control-Max-Age' 1728000;

    sendfile        on;
    keepalive_timeout  65;

    upstream admin { server admin}
    upstream iam { server iam_api:8000; }
    upstream fulfillment { server fulfillment_api:8000; }
    upstream cms { server cms_api:8000; }
    upstream catalog { server catalog_api:8000; }



    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri$args $uri$args/ $uri $uri/ ;
        }

        location /admin {
            proxy_pass "http://admin"
            proxy_set_header Host $host;
            client_max_body_size 20M;
            keepalive_timeout 0;
        }

        location /api/iam {
            proxy_pass "http://iam";
            proxy_set_header Host $host;
            client_max_body_size 20M;
            keepalive_timeout 0;
        }

       location /api/fulfillment {
            proxy_pass "http://fulfillment";
            proxy_set_header Host $host;
            client_max_body_size 20M;
            keepalive_timeout 0;
        }

        location /api/cms {
            proxy_pass "http://cms";
            proxy_set_header Host $host;
            client_max_body_size 20M;
            keepalive_timeout 0;
        }

        location /api/catalog {
            proxy_pass "http://catalog";
            proxy_set_header Host $host;
            client_max_body_size 20M;
            keepalive_timeout 0;
        }


        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}
