// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';
import {IEnvironment} from '@env/environment.interface';
import {version} from '../../package.json';

export const environment: IEnvironment = {
  production: true,
  BASE_API_URL: '/api',
  FB_APPLICATION_ID: '700626284166786',
  GOOGLE_APPLICATION_ID: '50988981071-qebioumemg77jogdg54oe98be1qifaum.apps.googleusercontent.com',
  SHIPPING_COUNTRY_CODE: 'IDN',
  YOUTUBE_API_KEY: 'AIzaSyB7m0r7paaV5I5U6vjf0pDmocvD8-K-D-w',
  elasticAPM: {
    serviceName: 'Nusantara-Web-MT',
    serverUrl: 'https://f51291eec6a94ce2a7309a312be33aa7.apm.ap-southeast-1.aws.cloud.es.io:443',
    serviceVersion: version,
    debug: false,
    active: true,
    environment: 'production',
    breakdownMetrics: true,
    distributedTracingOrigins: [ ],
    ignoreTransactions: [],
  }
};
