// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import {IEnvironment} from '@env/environment.interface';
import {version} from '../../package.json';

export const environment: IEnvironment = {
  production: false,
  BASE_API_URL: '/api',
  FB_APPLICATION_ID: '657992455041552',
  GOOGLE_APPLICATION_ID: '62419296650-d2cld4t7a0kfm8cvv2pk8sb51epvos62.apps.googleusercontent.com',
  SHIPPING_COUNTRY_CODE: 'IDN',
  YOUTUBE_API_KEY: 'AIzaSyB7m0r7paaV5I5U6vjf0pDmocvD8-K-D-w',
  elasticAPM: {
    serviceName: 'MT-Local-Web',
    serverUrl: 'https://apm.bhisma.cloud',
    serviceVersion: version,
    debug: true,
    active: true,
    environment: 'development',
    breakdownMetrics: true,
    distributedTracingOrigins: [ ],
    ignoreTransactions: [],
  }
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
