export const DEFAULT_WIDTH_BRANDS_DESKTOP = 211;
export const DEFAULT_HEIGHT_BRANDS_DESKTOP = 211;

export const DEFAULT_WIDTH_BRANDS_MOBILE =  90;
export const DEFAULT_HEIGHT_BRANDS_MOBILE =  90;

export const DEFAULT_WIDTH_TESTIMONIAL_DESKTOP = 196;
export const DEFAULT_HEIGHT_TESTIMONIAL_DESKTOP = 196;

export const DEFAULT_WIDTH_LOGO_HEADER_DESKTOP = 280;
export const DEFAULT_HEIGHT_LOGO_HEADER_DESKTOP = 40;
